# Site settings
title: kate hollenbach DOT COM
email: kjhollen@alum.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Kate Hollenbach, a designer and programmer in Los Angeles.
baseurl: ""
url: "http://localhost:4000"
twitter_username: kjhollen
github_username:  kjhollen
collections:
  work:
    output: true

# Build settings
markdown: kramdown

